### ISSUE TITLE
[Suggestions] Please provide an option for callers to specify genes to be analysed

### ISSUE THREAD

**Issue by davidyuyuan** [PacificBiosciences/pb-StarPhase#13]
I have a couple of suggestions from user's perspecitve. Please let me know if they are sensible or you have plans to look into them already.

1. The current implementation of the tool analyses all 21 genes it supports. It would be nice to allow callers to specify which gene(s) to be analysed.
2. Some options are always required (e.g. --vcf, --reference and --output-calls). Different genes / kind of analyses may require different input options. Perhaps, calling diplotype of HLA genes or CYP2D6 may not need --vcf.
3. There are a large amount of Some warning messages sent to STDOUT / STDERR. Perhaps, some of them can be suppressed, similar to the behaviour of HiFiHLA?

**Comment by holtjma** [comment]
Hi, thanks for the suggestions, here's some comments on each:

1. Currently this is controlled by the database itself. If you want to remove some genes from the output, you can delete their entry in the database and re-run the tooling.  The exception here may be HLA and CYP2D6, they may not handle the inclusion of a BAM and the absence of database correctly.  I would need to verify that.
2. That's right, currently HLA and CYP2D6 are only enabled if a BAM file is provided.  All the other genes use the input VCF. We can likely make it optional (disabling all VCF-based genes when a VCF is not provided), it's something we floated before but have not implemented yet.
3. There shouldn't be anything sent to stdout currently.  There also should not be many warnings (two variants in the default database are always warnings), is there something in particular you are seeing a lot of?  If you just don't want to see output, I would suggest redirecting it to a log file or `/dev/null`.

**Comment by davidyuyuan** [comment]
Thank you, Matt. 
1. Thank you for sharing the insights. I will try it out.
2. I quite like the idea. Once you get a chance to make --vcf optional, I will test it out.
3. I was referring to similar warning messages that you and I discussed in https://github.com/PacificBiosciences/HiPhase/issues/32. Let me try to recapture such messages to give you a better idea which ones I was referring to.

**Comment by davidyuyuan** [comment]
Please see the warning messages below in a snippet of the log below. Perhaps, turn them into debug messages as what you did before?
```
[2024-05-16T20:37:22.261Z INFO  pbstarphase] Loading PGx database from "/home/jovyan/pgxdash/pgxtools/variants/cpic_json_db.json"...
[2024-05-16T20:38:31.205Z INFO  pbstarphase] Loading reference genome from "/home/jovyan/work/GRCh38/GRCh38_full_analysis_set_plus_decoy_hla.fa"...
[2024-05-16T20:38:48.434Z INFO  pbstarphase::diplotyper] Solving ABCG2...
[2024-05-16T20:38:48.913Z WARN  pbstarphase::diplotyper] Received 'error seeking to "chr4":88131120 in indexed file', while seeking to chr4:88131120-88131220, assuming no variants present
[2024-05-16T20:38:48.914Z INFO  pbstarphase::diplotyper] Solving CACNA1S...
[2024-05-16T20:38:49.004Z WARN  pbstarphase::diplotyper] Received 'error seeking to "chr1":201091942 in indexed file', while seeking to chr1:201091942-201092042, assuming no variants present
[2024-05-16T20:38:49.004Z WARN  pbstarphase::diplotyper] Received 'error seeking to "chr1":201060764 in indexed file', while seeking to chr1:201060764-201060864, assuming no variants present
```

**Comment by holtjma** [comment]
Ah, I see.  I have not encountered these during testing due to having complete VCF files.  In HiPhase, those warnings were much more often created for less important contigs (e.g., ALT).  In StarPhase, if this message pops up it means that a region that was specifically searched for containing _relevant_ variants was not found.  For now at least, we will be keeping the warnings to highlight that something may be wrong with the user input.

**Comment by holtjma** [comment]
We made some changes as part of v0.10.2 to address the above issues. It's available here: https://github.com/PacificBiosciences/pb-StarPhase/releases/tag/v0.10.2

Thanks for the feedback!
