### ISSUE TITLE
Pbstarphase missed *36 in UGT1A1 in NA19207

### ISSUE THREAD

**Issue by davidyuyuan** [PacificBiosciences/pb-StarPhase#26]
The diplotype of UGT1A1 was called as *36/[*80+*28] in older versions. The BAM of NA19207 was from [Twist Alliance Long Read PGx Panel](https://programs.pacb.com/l/1652/2023-06-07/43zbq2?_gl=1*15i97r0*_gcl_au*MTM1NzQ5MTQ5Ny4xNzE1Njc0NTcy*_ga*NDg1ODQ4MTA1LjE2OTc5MDUzNzU.*_ga_TSCERCM0J4*MTcyMjUzOTczMy40NS4xLjE3MjI1Mzk3MzMuMC4wLjA.).

In the latest version v.0.13.0, the diplotype was called as *1/[*80+*28]. The visual inspection with IGV seemed support *36/[*80+*28] more. 

Note that the insertion does look messy, ranging from 0, 2, 4 to 6. However, *1 or 0 insertion is the least likely the case.

![NA19207_UTG1A1_36](https://github.com/user-attachments/assets/60f56aa5-9fcb-4154-8a01-706464c8ee74)

**Comment by holtjma** [comment]
Hi @davidyuyuan,

I can say with relatively high confidence that none of the changes related to v0.13.0 (really, going all the way back to v0.8.0) should have impacted the VCF caller, which is what _UGT1A1_ is called with.  This means that the most likely reason for the change is an alteration of the upstream database (specifically, CPIC's database for this gene).  Can you provide the last version where you saw the *36 allele and the version where it changed to *1? I suspect the allele definitions changed.

Matt

**Comment by davidyuyuan** [comment]
"I should note an alternate hypothesis is that the VCF file changes." I will compare the VCFs if we still have them saved.

**Comment by davidyuyuan** [comment]
It was a change in the behaviour of variant normalization introduced in bcftools v1.20. Thank you for the help. I have got *36/[*80+*28] now.

**Comment by holtjma** [comment]
Great, glad you were able to identify the change.

> I only have access to the latest version of the CPIC database: https://api.cpicpgx.org/v1/allele_definition?genesymbol=eq.UGT1A1&select=genesymbol,name,allele_location_value(variantallele,%20sequence_location(name,dbsnpid,position))&order=name, which is not very helpful :)

Just for future reference: Inside the pb-StarPhase database file, there's a section for each gene.  So what I was saying was you could compare the internal JSON components to see if there was a difference.  For example, [this is what one of the original DB entries we published looks like for UGT1A1](https://github.com/PacificBiosciences/pb-StarPhase/blob/77862734b1099ea6d4a44e369a74531354dd8f16/data/v0.6.1/cpic_20230914.json#L10081). I know you're running the `build` command yourself, so it's something you would need to check for your local DB files.

In this case, it sounds like it was not a DB issue but the VCF instead.

**Comment by davidyuyuan** [comment]
Thank you, Matt!

I added -a option to norm trying to make use of improvements in Bcftools in 1.20 to make variants more atomic. It made some incorrect INDEL calls. The problem was solved after removing the -a option.
