### ISSUE TITLE
More details of PharmCAT comparison problem

### ISSUE THREAD

**Issue by whaleyr** [PacificBiosciences/pb-StarPhase#6]
I'm one of the developers on PharmCAT and I just noticed on your [performance.md file](https://github.com/PacificBiosciences/pb-StarPhase/blob/main/docs/performance.md) that you say:

> it appeared that PharmCAT was erroneously treating variants in different phase blocks as being in phase with each other. This created haplotypes that have not been described before and led to the "Unknown/Unknown" reports.

Have you reported this as an issue in the PharmGKB/PharmCAT repo? If not, could you please submit an issue with more details and hopefully a synthetic example that we can use to reproduce the error?

Thanks for documenting your comparison and performance data. We're really interested in seeing how people use PharmCAT and what they're expectations are.

**Comment by holtjma** [comment]
Hey Ryan,

I haven't reported it, I was under the impression (perhaps falsely) that it had already been reported as an issue.  I'll see if I can dig up the dataset with the Unknown report, but if not I should be able to mock it with relative ease.

To give you a taste, the gist of it is that PharmCAT doesn't seem to recognize the PS (Phase Set) tag, and is just assuming that everything is in one phase block. This leads to erroneous phasing that can produce either incorrect results or (more often) Unknown/Unknown.

I'll try to submit that later today!
Matt

**Comment by holtjma** [comment]
As a note to myself: that performance file likely needs to be updated the next time we update the tool. PharmCAT is several versions ahead and the counting script may need to be revisited with our format changes.

Going to close this out now, @whaleyr let me know if you need more info in the created PharmCAT ticket!
